### ISSUE TITLE
Shortcircuit after first invokeDestroy in org.zeroturnaround.process.OrProcess destroy

### ISSUE THREAD

**Issue by ghost** [zeroturnaround/zt-process-killer#1]
Is the for-loop supposed to short-circuit after the first invokeDestroy()? Or is it supposed to invoke destroy on all the children?

Just wondering how that works.

@Override
  public void destroy(boolean forceful) throws IOException, InterruptedException {
    for (SystemProcess child : children) {
      try {
        invokeDestroy(child, forceful);
        return;
      }
      catch (UnsupportedOperationException e) {
        // continue
      }
    }
    throw new UnsupportedOperationException();
  }

**Comment by ghost** [comment]
Just asking because I have a process that will not kill and with the composite SystemProcess, the first one it tries is the usual Java Process, which reports that it has dies, but has not in fact died.

But if it tried the pidProcess as well, then it would have died. So I have changed my code to use PID process exclusively, but it woiul dbe nice if the standrad SystemProcess that is created with process and pid also worked.

I can send you a test exe if you wish that shows that it does not die unless taskkilled.

**Comment by reinra** [comment]
Thanks for the question.
Yes, it's supposed to work like that. It's the difference between OrProcess and AndProcess.
However destroy(boolean) doesn't guarantee that a process is destroyed. It only guarantees that it was signalled - so you always have to wait as well. Plus if it's a graceful signal the process can choose by itself whether it wants to stop or not. That's why it's always necessary to fallback to forceful signal. So invoking

``` java
ProcessUtil.destroyGracefullyOrForcefullyAndWait(process, 30, TimeUnit.SECONDS, 10, TimeUnit.SECONDS);
```

should always stop the process (unless system is just unable to kill it within 10 seconds) - even if it's an OrProcess.
